import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f9f9f9",
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 40,
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f2f2f2",
        borderRadius: 16,
        paddingHorizontal: 14,
        height: 52,
        marginBottom: 16,
    },
    currencyPrefix: {
        fontSize: 18,
        fontWeight: "600",
        color: "#555",
        marginRight: 6,
    },
    amountInput: {
        flex: 1,
        fontSize: 18,
        fontWeight: "600",
        color: "#333",
    },
    loadBtn: {
        backgroundColor: "#4A4A4A",
        borderRadius: 25,
        height: 58,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        marginTop: 4,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 6,
    },
    loadBtnDisabled: {
        opacity: 0.6,
    },
    loadBtnText: {
        fontSize: 17,
        fontWeight: "700",
        color: "#fff",
        letterSpacing: 0.3,
    },
    secureNote: {
        textAlign: "center",
        fontSize: 12,
        color: "#aaa",
        marginTop: 14,
    },
    targetSelector: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
    },
    targetLabel: {
        fontSize: 13,
        fontWeight: "700",
        color: "#4A4A4A",
        marginBottom: 12,
    },
    targetOptions: {
        flexDirection: "row",
        gap: 10,
    },
    targetOption: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: "#e0e0e0",
        backgroundColor: "#f9f9f9",
    },
    targetOptionActive: {
        backgroundColor: "#4A4A4A",
        borderColor: "#4A4A4A",
    },
    targetOptionText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#555",
    },
    targetOptionTextActive: {
        color: "#fff",
    },
});